"""Parser for Microsoft Visio files (.vsdx, .vsd, etc.)"""

from pathlib import Path

from django.conf import settings
from gotenberg_client import GotenbergClient
from gotenberg_client.options import PdfAFormat

from documents.parsers import DocumentParser, make_thumbnail_from_pdf
from paperless.models import OutputTypeChoices


class VisioDocumentParser(DocumentParser):
    """Parser for Microsoft Visio files with native VSDX extraction and PDF conversion."""

    logging_name = "paperless.parsing.visio"

    def get_settings(self):
        return None

    def parse(self, document_path: Path, mime_type: str, file_name: str = None):
        """Extract text from Visio file and generate PDF archive."""
        document_path = Path(document_path)
        file_ext = document_path.suffix.lower()

        # VSDX/VSDM: native extraction then PDF
        if file_ext in {".vsdx", ".vsdm"}:
            self._parse_vsdx_native(document_path)
            self.archive_path = self._convert_to_pdf(document_path)
        # Other formats: PDF then extract text from PDF
        else:
            self.archive_path = self._convert_to_pdf(document_path)
            if self.archive_path:
                self._extract_text_from_pdf(self.archive_path)
            else:
                self.text = ""

    def get_thumbnail(self, document_path: Path, mime_type: str, file_name=None) -> Path:
        """Generate thumbnail from PDF."""
        if not self.archive_path:
            self.archive_path = self._convert_to_pdf(document_path)
        return make_thumbnail_from_pdf(self.archive_path, self.tempdir, self.logging_group)

    def _parse_vsdx_native(self, document_path: Path):
        """Extract text from VSDX using vsdx library."""
        import vsdx

        text_parts = []
        with vsdx.VisioFile(str(document_path)) as visio_file:
            for page in visio_file.pages:
                for shape in page.all_shapes:
                    try:
                        if shape.text and (text := shape.text.strip()) and text != "Obj":
                            text_parts.append(text)
                        if hasattr(shape, "data") and shape.data:
                            text_parts.extend(f"{k}: {v}" for k, v in shape.data.items() if v)
                    except Exception:
                        continue

        self.text = "\n".join(text_parts)
        self.log.info(f"Extracted {len(self.text)} characters from {document_path.name}")

    def _convert_to_pdf(self, document_path: Path) -> Path:
        """Convert Visio file to PDF using Gotenberg."""
        pdf_path = Path(self.tempdir) / f"{document_path.stem}.pdf"

        with GotenbergClient(
            host=settings.TIKA_GOTENBERG_ENDPOINT,
            timeout=settings.CELERY_TASK_TIME_LIMIT,
        ) as client, client.libre_office.to_pdf() as route:
            # Set PDF/A format based on settings
            if settings.OCR_OUTPUT_TYPE in {OutputTypeChoices.PDF_A, OutputTypeChoices.PDF_A2, OutputTypeChoices.PDF_A1}:
                route.pdf_format(PdfAFormat.A2b)
            elif settings.OCR_OUTPUT_TYPE == OutputTypeChoices.PDF_A3:
                route.pdf_format(PdfAFormat.A3b)

            route.convert(document_path)
            pdf_path.write_bytes(route.run().content)

        return pdf_path

    def _extract_text_from_pdf(self, pdf_path: Path):
        """Extract text from PDF generated by LibreOffice/Gotenberg."""
        from pdfminer.high_level import extract_text

        self.text = extract_text(pdf_path).strip()
        self.log.info(f"Extracted {len(self.text)} characters from PDF")
